# Generated by Django 4.2.5 on 2025-05-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.categoria'),
        ),
    ]
