# Generated by Django 4.2.5 on 2025-05-12 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='fecha_fin',
            new_name='desde',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='tipo',
        ),
        migrations.AddField(
            model_name='alert',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='hasta',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='tipo_aviso',
            field=models.CharField(choices=[('popup', 'Pop-up'), ('email', 'Email'), ('color', 'Cambio de color')], default='informativo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
