# Generated by Django 4.2.5 on 2025-05-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_fecha_fin_alert_desde_remove_alert_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
