# Generated by Django 4.2.5 on 2025-05-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='progreso',
        ),
    ]
