# Generated by Django 4.2.5 on 2025-05-12 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_remove_alert_user_alter_alert_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='tipo',
            field=models.CharField(choices=[('popup', 'Notificación'), ('color', 'Cambio de color')], max_length=10),
        ),
    ]
