# Generated by Django 4.2.5 on 2025-05-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alert_user_alter_alert_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
